### ISSUE TITLE
IA/IB Mixed up

### ISSUE THREAD

**Issue by ichrispa** [oowekyala/arm-cheatsheet#1]
Hi @oowekyala 

love your cheat sheet. I think you've run into a tiny mixup with the LDM/STM modes:
* IA will start at reg
* IB will start at reg + 4

Otherwise, `stmfd sp!,{lr}`  would be overwriting the link register on the stack; it isn't, because stmfd increments before storing.

Could you please fix that?

Best regards,

ichrispa

**Comment by oowekyala** [comment]
Hi, thanks for reporting this! You're right, I'll fix it.
